<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'applicationbasetestcase' => '/tests/ApplicationBaseTestCase.php',
                'basetestcase' => '/tests/BaseTestCase.php',
                'container' => '/dsl/Container.php',
                'fillelementstest' => '/tests/Selenium2TestCase/FillElementsTest.php',
                'homepage' => '/tests/Pages/HomePage.php',
                'loginpage' => '/tests/Pages/LoginPage.php',
                'menu' => '/dsl/Menu.php',
                'page' => '/dsl/Page.php',
                'projectpage' => '/ProjectPage.php',
                'tab' => '/dsl/Tab.php',
                'windowform' => '/dsl/WindowForm.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd